version: '3.8'

services:
  peer1:
    container_name: peer1
    build: .
    command: python /app/main.py
    restart: on-failure
    ports:
      - 15001:15001
    environment:
      - PEER_ID=1
      - PEER_HOST=peer1
      - PEER_PORT=15001
    volumes:
      - .:/app
  peer2:
    container_name: peer2
    build: .
    command: python /app/main.py
    restart: on-failure
    ports:
      - 15002:15002
    environment:
      - PEER_ID=2
      - PEER_HOST=peer2
      - PEER_PORT=15002
    volumes:
      - .:/app
  peer3:
    container_name: peer3
    build: .
    command: python /app/main.py
    restart: on-failure
    ports:
      - 15003:15003
    environment:
      - PEER_ID=3
      - PEER_HOST=peer3
      - PEER_PORT=15003
    volumes:
      - .:/app
  peer4:
    container_name: peer4
    build: .
    command: python /app/main.py
    restart: on-failure
    ports:
      - 15004:15004
    environment:
      - PEER_ID=4
      - PEER_HOST=peer4
      - PEER_PORT=15004
    volumes:
      - .:/app
  peer5:
    container_name: peer5
    build: .
    command: python /app/main.py
    restart: on-failure
    ports:
      - 15005:15005
    environment:
      - PEER_ID=5
      - PEER_HOST=peer5
      - PEER_PORT=15005
    volumes:
      - .:/app